---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: ws
  namespace: default
spec:
  template:
    metadata:
    spec:
      containers:
      - image: nimak/websocket-app:v1
        env:
        - name: SERVING_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
